#!/bin/bash

CONFIG=/boot/recalbox-boot.conf

function set_config(){

    oldvalue=`grep $1= $CONFIG | cut -d "=" -f 2`
    if [ -z $oldvalue ]; then
        echo $1=$2 >> $CONFIG
    else
        cat $CONFIG | sed "s/^\($1\s*=\s*\).*\$/\1$2/" >$CONFIG.new
        cp $CONFIG.new $CONFIG
        rm $CONFIG.new
    fi
}

audiovolume=`grep audio.volume= /recalbox/share/system/recalbox.conf | cut -d "=" -f 2`
audiodevice=`grep audio.device= /recalbox/share/system/recalbox.conf | cut -d "=" -f 2`

if [ ! -z $audiovolume ]; then
    set_config audio.volume ${audiovolume}
fi

if [ ! -z $audiodevice ]; then
    set_config audio.device ${audiodevice}
fi
