#!/bin/bash

do_start () 
{
    if test -e "/recalbox/system/resources/splash/recalbox.mov"; then
        #omxplayer -b --layer 1000 "/recalbox/system/resources/splash/recalbox.mov"a
	/recalbox/system/resources/splash/CreateSubT.sh
        omxplayer --layer 10000 --alpha 224 --aspect-mode fill --subtitles "/tmp/subtitle.srt" --align left --no-ghost-box "/recalbox/system/resources/splash/recalboxIntro.mp4"
    else
        fbv -f -i /recalbox/system/resources/splash/logo-version.png
    fi
}

case "$1" in
    start)
        do_start &
        ;;
    stop)
	   ;;
    restart|reload)
	   ;;
    *)
esac

exit $?
