#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
 	echo "Starting network..."
	/sbin/ifup -a
	;;
  stop)
      if grep -qE '^[ ]*sharedevice[ ]*=[ ]*NETWORK[ ]*$' /boot/recalbox-boot.conf
      then
	  echo "Network must not be stopped on NETWORK share"
	  exit 1
      fi
	printf "Stopping network..."
	/sbin/ifdown -a
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

